OnlineShopDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path("accounts/", include("accounts.urls", namespace="accounts")),
                  path('cart/', include('cart.urls', namespace="cart")),
                  path('orders/', include('orders.urls', namespace='orders')),
                  path('', include('shop.urls', namespace='shop')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.detail, name="detail"),
    path('add/<int:product_id>/', views.cart_add, name="cart_add"),
    path('remove/<int:product_id>', views.cart_remove, name="cart_remove")
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('<int:order_id>/', views.detail, name='orders_detail'),
    path('apply/<int:order_id>/', views.coupon_apply, name='coupon_apply'),
    path('', views.create, name='orders_create'),

]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


class CartAddForm(forms.Form):
    quantity = forms.IntegerField(initial=1, min_value=1, max_value=9,
                                  widget=forms.NumberInput(attrs={'class': 'form-control'}))

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .cart import Cart
from shop.models import Product
from .forms import CartAddForm
from django.views.decorators.http import require_POST
from django.contrib import messages


def detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'])
        messages.success(request, f'{cd["quantity"]} {product.name} added successfully to your cart', 'success')
    return redirect("shop:product_detail", product.slug)


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("cart:detail")

cart/templates/cart/detail.html
{% extends 'base.html' %}
{% block title %}
    Cart
{% endblock title %}
{% block content %}
    <table class="table table-dark">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Product</th>
            <th scope="col">Quantity</th>
            <th scope="col">Unit Price</th>
            <th scope="col">Total Price</th>
            <th scope="col">Remove</th>
        </tr>
        </thead>
        <tbody>
        {% for i in cart %}


            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ i.product }}</td>
                <td>{{ i.quantity }}</td>
                <td>{{ i.price }}</td>
                <td>{{ i.total_price }}</td>
                <td><a href="{% url "cart:cart_remove" i.product.id %}">Remove</a></td>


            </tr>
        {% endfor %}
        <tr>
            <td>Total</td>
            <td colspan="3"></td>
            <td>{{ cart.get_total_price }}</td>
        </tr>
    </table>
    <a class="btn btn-primary" href="{% url "orders:orders_create" %}">CheckOut</a>
{% endblock content %}